version: '3.1'

services:

  app:
    image: go-git-app
    restart: always
    ports: 
      - "5000:80"
    environment:
      - API_ADDR=http://api:4000
    depends_on:
      - api

  api:
    image: go-git-api
    restart: always
    expose: 
      - "4000"
    environment:
      - APP_SERVER_PORT=4000
      - GIT_DB_CONN_STRING=admin:admin@tcp(db)/gogit
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    volumes:
      - gitappdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=gogit

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

volumes:
  gitappdata: