export const ActionType = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_REPOSITORIES: 'SET_REPOSITORIES',
    SET_CURRENT_REPOSITORY: 'SET_CURRENT_REPOSITORY',
    REMOVE_REPO: 'REMOVE_REPO',
    SET_CURRENT_BRANCH: 'SET_CURRENT_BRANCH',
    SET_BRANCHES: 'SET_BRANCHES',
    REMOVE_BRANCH: 'REMOVE_BRANCH',
    SHOW_MSG: 'SHOW_MSG',
    RESET_MSG: 'RESET_MSG',
    SET_FILES: 'SET_FILES'

    /* SHOW_SPINNER: 'SHOW_SPINNER',
    HIDE_SPINNER: 'HIDE_SPINNER', */
}