export const ActionType = {
    SET_USERS: 'SET_USERS',
    SET_REPOSITORIES: 'SET_REPOSITORIES',
    SET_BRANCHES: 'SET_BRANCHES',
    SHOW_MSG: 'SHOW_MSG',
    RESET_REPO: 'RESET_REPO',
    RESET_BRANCH: 'RESET_BRANCH',
    SET_FILES: 'SET_FILES'

    /* SHOW_SPINNER: 'SHOW_SPINNER',
    HIDE_SPINNER: 'HIDE_SPINNER', */
}